function data()
return {
	en = {
		["mod_name"] = "ICE 3 (Class 403/406) of Deutsche Bahn",
		["mod_desc"] = "As the successor to ICE 1 and 2, the third generation of the ICE was put into operation in the year of 2000 right in time for the EXPO in Hanover. They are the first trains of Deutsche Bahn that can reach a top speed of 330 km/h. In contrast to the older ICE generations, there are no longer any multiple units, but the drives are distributed underfloor across the entire train.\nThere are two different series: the multi-system train with approval for Germany, Switzerland, Austria, France, the Netherlands and Belgium carries the designation 406, the single-system trains are run as series 403.\nThis mod also contains the fake variant of all vehicles. These can be activated with the in-game mod manager if necessary.",

        ["Fake"] = "Activate fake versions?",
        ["option_fake_ice3_desc"] = "You can choose if fake versions of the ICE 3 should be hidden (default) or shown in depot.",

        ["ICE3_menu"] = "ICE 3 (Class 403/Class 406)",
		["ICE3_BR403_1_name"] = "ICE 3 (Class 403 - 1. series)",
        ["ICE3_BR403_1_gruen_name"] = "ICE 3 (Class 403 - 1. series) \"Green electricity\"",
        ["ICE3_BR403_1_klima_name"] = "ICE 3 (Class 403 - 1. series) \"Climate saver\"",
        ["ICE3_BR406_1_name"] = "ICE 3 (Class 406 - 1. series)",
        ["ICE3_BR406_1_gruen_name"] = "ICE 3 (Class 406 - 1. series) \"Green electricity\"",
        ["ICE3_BR406_1_klima_name"] = "ICE 3 (Class 406 - 1. series) \"Climate saver\"",
        ["ICE3_BR406_1_europa_name"] = "ICE 3 (Class 406 - 1. series) Europe",
        ["ICE3_BR406_1_NS_name"] = "ICE 3 (Class 406 - 1. series) Nederlandse Spoorwegen",
        ["ICE3_BR406_1_hispeed_name"] = "ICE 3 (Class 406 - 1. series) NS hispeed",
        ["ICE3_BR403_1_pride_name"] = "ICE 3 (BR 403 - 1. Serie) Pride",

        ["ICE3_BR403_2_name"] = "ICE 3 (Class 403 - 2. series)",
        ["ICE3_BR403_2_gruen_name"] = "ICE 3 (Class 403 - 2. series) \"Green electricity\"",
        ["ICE3_BR403_2_klima_name"] = "ICE 3 (Class 403 - 2. series) \"Climate saver\"",
        ["ICE3_BR406_2_name"] = "ICE 3 (Class 406 - 2. Serie)",
        ["ICE3_BR406_2_gruen_name"] = "ICE 3 (Class 406 - 2. series) \"Green electricity\"",
        ["ICE3_BR406_2_klima_name"] = "ICE 3 (Class 406 - 2. series) \"Climate saver\"",
		["ICE3_BR403_1_desc"] = "As the successor to the first two ICE generations, the ICE 3 was the first Deutsche Bahn train that could reach a top speed of 330 km/h. In addition, it no longer had power cars, but the drive was built underfloor in almost all cars. The 403 series is the single-system variant for use in Germany only. The trains of the 1st series had large air conditioning units on the roof. ",
        ["ICE3_BR406_1_desc"] = "As the successor to the first two ICE generations, the ICE 3 was the first Deutsche Bahn train that could reach a top speed of 330 km/h. In addition, it no longer had power cars, but the drive was built underfloor in almost all cars. The 406 series is the multi-system variant for use in Germany and some neighboring European countries. The trains of the 1st series had large air conditioning units on the roof.",
        ["ICE3_BR406_1_NS_desc"] = "After Deutsche Bahn AG ordered the new ICE 3 trains in 1994, the Nederlandse Spoorwegen N.V. also ordered 4 trains of the multi-system series. They are also referred to as BR 406, but bear the NS logo. The top speed in the Netherlands is 140 km/h.",
        ["ICE3_BR406_1_hispeed_desc"] = "AIn 2010 the new NS hispeed logo was installed on train 4654. Probably also on the other trains in the series, but it was probably removed again in 2012. Nothing changed in use.",
        ["ICE3_BR403_2_desc"] = "As the successor to the first two ICE generations, the ICE 3 was the first Deutsche Bahn train that could reach a top speed of 330 km / h. In addition, it no longer had power cars, but the drive was built underfloor in almost all cars. The 403 series is the single-system variant for use in Germany. The trains of the 2nd series had flat air conditioning units on the roof. ",
        ["ICE3_BR406_2_desc"] = "As the successor to the first two ICE generations, the ICE 3 was the first Deutsche Bahn train that could reach a top speed of 330 km/h. In addition, it no longer had power cars, but the drive was built underfloor in almost all cars. The 406 series is the multi-system variant for use in Germany and some neighboring European countries. The trains of the 2nd series had flat air conditioning units on the roof.",
        ["ICE3_gruen_desc"] = " In 2018 the DB AG started the campaign \"Grünspotting\" in which one should view and photograph some ICE 3 trains with green stripes.",
        ["ICE3_klima_desc"] = " Since 2019, the trains have been pasted with green stripes at the ends to indicate that the train runs on green electricity and is kind to the climate.",
        ["ICE3_pride_desc"] = "In July 2021, Deutsche Bahn AG put a rainbow band on its train to celebrate the 10th anniversary of its LGBTIQ * employee network.",
        ["ICE3_BR406_europa_desc"] = "For the European elections in 2018, a class 406 train was christened Europa and covered with a blue stripe.",

        ["ICE3_Apmzf403.0_name"] = "1st class end car Apmzf 403.0",
        ["ICE3_Avmz403.1_name"] = "1st class car Avmz 403.1",
        ["ICE3_Bvmz403.2_name"] = "2nd class car Bvmz 403.2",
        ["ICE3_BRmz403.3_name"] = "Bordbistro/2nd class car BRmz 403.3",
        ["ICE3_BRmz403.3_restaurant_name"] = "Restaurant car WRmz 403.3",
        ["ICE3_Bpmbz403.8_name"] = "2nd class service car Bpmbz 403.8",
        ["ICE3_Bpmz403.7_name"] = "2nd class car Bpmz 403.7",
        ["ICE3_Bpmz403.6_name"] = "2nd class car Bpmz 403.6",
        ["ICE3_Bpmzf403.5_name"] = "2nd class end car Bpmzf 403.5",

        ["ICE3_Apmzf406.0_name"] = "1st class end car Apmzf 406.0",
        ["ICE3_Avmz406.1_name"] = "1st class car Avmz 406.1",
        ["ICE3_Bvmz406.2_name"] = "2nd class car Bvmz 406.2",
        ["ICE3_BRmz406.3_name"] = "Bordbistro/2nd class car BRmz 406.3",
        ["ICE3_BRmz406.3_restaurant_name"] = "Restaurant car BRmz 406.3",
        ["ICE3_Bpmbz406.8_name"] = "2nd class service car Bpmbz 406.8",
        ["ICE3_Bpmz406.7_name"] = "2nd class car Bpmz 406.7",
        ["ICE3_Bpmz406.6_name"] = "2nd class car Bpmz 406.6",
        ["ICE3_Bpmzf406.5_name"] = "2nd class end car Bpmzf 406.5",

        ["ICE3_fake_menu"] = "ICE 3 (Class 403/Class 406) FAKE",
		["ICE3_BR403_1_fake_name"] = "ICE 3 (Class 403 - 1. series) FAKE",
        ["ICE3_BR403_1_gruen_fake_name"] = "ICE 3 (Class 403 - 1. series) \"Green electricity\" FAKE",
        ["ICE3_BR403_1_klima_fake_name"] = "ICE 3 (Class 403 - 1. series) \"Climate saver\" FAKE",
        ["ICE3_BR403_1_pride_fake_name"] = "ICE 3 (BR 403 - 1. Serie) Pride",
        ["ICE3_BR406_1_fake_name"] = "ICE 3 (Class 406 - 1. series) FAKE",
        ["ICE3_BR406_1_gruen_fake_name"] = "ICE 3 (Class 406 - 1. series) \"Green electricity\" FAKE",
        ["ICE3_BR406_1_klima_fake_name"] = "ICE 3 (Class 406 - 1. series) \"Climate saver\" FAKE",
        ["ICE3_BR406_1_europa_fake_name"] = "ICE 3 (Class 406 - 1. series) Europe FAKE",
        ["ICE3_BR406_1_NS_fake_name"] = "ICE 3 (Class 406 - 1. series) Nederlandse Spoorwegen FAKE",
        ["ICE3_BR406_1_hispeed_fake_name"] = "ICE 3 (Class 406 - 1. series) NS hispeed FAKE",

        ["ICE3_Apmzf403.0_fake_name"] = "1st class end car Apmzf 403.0 FAKE",
        ["ICE3_Avmz403.1_fake_name"] = "1st class car Avmz 403.1 FAKE",
        ["ICE3_Bvmz403.2_fake_name"] = "2nd class car Bvmz 403.2 FAKE",
        ["ICE3_BRmz403.3_fake_name"] = "Bordbistro/2nd class car BRmz 403.3 FAKE",
        ["ICE3_BRmz403.3_restaurant_fake_name"] = "Restaurant car WRmz 403.3 FAKE",
        ["ICE3_Bpmbz403.8_fake_name"] = "2nd class service car Bpmbz 403.8 FAKE",
        ["ICE3_Bpmz403.7_fake_name"] = "2nd class car Bpmz 403.7 FAKE",
        ["ICE3_Bpmz403.6_fake_name"] = "2nd class car Bpmz 403.6 FAKE",
        ["ICE3_Bpmzf403.5_fake_name"] = "2nd class end car Bpmzf 403.5 FAKE",

        ["ICE3_Apmzf406.0_fake_name"] = "1st class end car Apmzf 406.0 FAKE",
        ["ICE3_Avmz406.1_fake_name"] = "1st class car Avmz 406.1 FAKE",
        ["ICE3_Bvmz406.2_fake_name"] = "2nd class car Bvmz 406.2 FAKE",
        ["ICE3_BRmz406.3_fake_name"] = "Bordbistro/2nd class car BRmz 406.3 FAKE",
        ["ICE3_BRmz406.3_restaurant_fake_name"] = "Restaurant car BRmz 406.3 FAKE",
        ["ICE3_Bpmbz406.8_fake_name"] = "2nd class service car Bpmbz 406.8 FAKE",
        ["ICE3_Bpmz406.7_fake_name"] = "2nd class car Bpmz 406.7 FAKE",
        ["ICE3_Bpmz406.6_fake_name"] = "2nd class car Bpmz 406.6 FAKE",
        ["ICE3_Bpmzf406.5_fake_name"] = "2nd class end car Bpmzf 406.5 FAKE",
	},
	de = {
		["mod_name"] = "ICE 3 (BR 403/406) der Deutschen Bahn",
		["mod_desc"] = "Als Nachfolger des ICE 1 und 2 wurde die dritte Generation des ICE zur EXPO in Hannover im Jahr 2000 in Betrieb genommen. Sie sind die ersten Züge der Deutsschen Bahn, die eine Höchstgeschwindigkeit von 330 km/h erreichen können. Im Gegensatz zu den älteren ICE-Generationen gibt es keine Triebwagen mehr, sondern die Antriebe sind Unterflur über den ganzen Zug verteilt.\nEs gibt zwei verschiedene Baureihen: der Mehrsystemzug mit Zulassung für Deutschland, Schweiz, Österreich, Frankreich, Niederlande und Belgien trägt die Baureihenbezeichnung 406, die Einsystemzüge werden als Baureihe 403 geführt.\nDieser Mod beinhaltet ausserdem die Fake-Variante von allen Fahrzeugen. Diese können mit dem Ingame-Mod-Manager bei Bedarf aktiviert werden.",

        ["Fake"] = "Fake-Versionen aktivieren?",
        ["option_fake_ice3_desc"] = "Schaltet die Fake-Versionen des ICE 3 ab (Standard) oder an.",

        ["ICE3_menu"] = "ICE 3 (BR 403/BR 406)",
		["ICE3_BR403_1_name"] = "ICE 3 (BR 403 - 1. Serie)",
        ["ICE3_BR403_1_gruen_name"] = "ICE 3 (BR 403 - 1. Serie) Ökostrom",
        ["ICE3_BR403_1_klima_name"] = "ICE 3 (BR 403 - 1. Serie) Klimaschützer",
        ["ICE3_BR406_1_name"] = "ICE 3 (BR 406 - 1. Serie)",
        ["ICE3_BR406_1_gruen_name"] = "ICE 3 (BR 406 - 1. Serie) Ökostrom",
        ["ICE3_BR406_1_klima_name"] = "ICE 3 (BR 406 - 1. Serie) Klimaschützer",
        ["ICE3_BR406_1_europa_name"] = "ICE 3 (BR 406 - 1. Serie) Europa",
        ["ICE3_BR406_1_NS_name"] = "ICE 3 (BR 406 - 1. Serie) Nederlandse Spoorwegen",
        ["ICE3_BR406_1_hispeed_name"] = "ICE 3 (BR 406 - 1. Serie) NS hispeed",
        ["ICE3_BR403_1_pride_name"] = "ICE 3 (BR 403 - 1. Serie) Pride",

        ["ICE3_BR403_2_name"] = "ICE 3 (BR 403 - 2. Serie)",
        ["ICE3_BR403_2_gruen_name"] = "ICE 3 (BR 403 - 2. Serie) Ökostrom",
        ["ICE3_BR403_2_klima_name"] = "ICE 3 (BR 403 - 2. Serie) Klimaschützer",
        ["ICE3_BR406_2_name"] = "ICE 3 (BR 406 - 2. Serie)",
        ["ICE3_BR406_2_gruen_name"] = "ICE 3 (BR 406 - 2. Serie) Ökostrom",
        ["ICE3_BR406_2_klima_name"] = "ICE 3 (BR 406 - 2. Serie) Klimaschützer",
		["ICE3_BR403_1_desc"] = "Als Nachfolger der ersten beiden ICE-Generationen war der ICE 3 der erste Zug der Deutschen Bahn, der eine Höchstgeschwindigkeit von 330 km/h erreichen konnte. Außerdem verfügte er über keine Triebköpfe mehr, sondern der Antrieb war Unterflur in fast allen Wagen verbaut. Die Baureihe 403 ist die Einsystemvariante für den Einsatz in Deutschland. Die Züge der 1. Serie hatten große Klimaaggregate auf dem Dach. ",
        ["ICE3_BR406_1_desc"] = "Als Nachfolger der ersten beiden ICE-Generationen war der ICE 3 der erste Zug der Deutschen Bahn, der eine Höchstgeschwindigkeit von 330 km/h erreichen konnte. Außerdem verfügte er über keine Triebköpfe mehr, sondern der Antrieb war Unterflur in fast allen Wagen verbaut. Die Baureihe 406 ist die Mehrsystemvariante für den Einsatz in Deutschland und einigen europäischen Nachbarländern. Die Züge der 1. Serie hatten große Klimaaggregate auf dem Dach.",
        ["ICE3_BR406_1_NS_desc"] = "Nachdem die Deutsche Bahn AG im Jahr 1994 die neuen Züge des ICE 3 bestellt hatte, bestellte die Nederlandse Spoorwegen N.V. 4 Züge der Mehrsystembaureihe. Sie werden ebenfalls als BR 406 bezeichnet, tragen aber das Logo der NS. In den Niederlanden liegt die Höchstgeschwindigkeit bei 140 km/h.",
        ["ICE3_BR406_1_hispeed_desc"] = "Im Jahr 2010 wurde auf dem Zug 4654 das neue Logo von NS hispeed angebracht. Vermutlich auch auf den anderen Zügen der Baureihe, 2012 wurde es aber vermutlich wieder entfernt. Im Einsatz änderte sich nichts.",
        ["ICE3_BR403_2_desc"] = "Als Nachfolger der ersten beiden ICE-Generationen war der ICE 3 der erste Zug der Deutschen Bahn, der eine Höchstgeschwindigkeit von 330 km/h erreichen konnte. Außerdem verfügte er über keine Triebköpfe mehr, sondern der Antrieb war Unterflur in fast allen Wagen verbaut. Die Baureihe 403 ist die Einsystemvariante für den Einsatz in Deutschland. Die Züge der 2. Serie hatten flache Klimaaggregate auf dem Dach. ",
        ["ICE3_BR406_2_desc"] = "Als Nachfolger der ersten beiden ICE-Generationen war der ICE 3 der erste Zug der Deutschen Bahn, der eine Höchstgeschwindigkeit von 330 km/h erreichen konnte. Außerdem verfügte er über keine Triebköpfe mehr, sondern der Antrieb war Unterflur in fast allen Wagen verbaut. Die Baureihe 406 ist die Mehrsystemvariante für den Einsatz in Deutschland und einigen europäischen Nachbarländern. Die Züge der 2. Serie hatten flache Klimaaggregate auf dem Dach.",
        ["ICE3_gruen_desc"] = " Im Jahr 2018 startete die DB AG die Kampagne \"Grünspotting\" bei der man einige ICE 3 mit grünem Streifen sichten und fotografieren sollte.",
        ["ICE3_klima_desc"] = " Seit 2019 werden die Züge mit grünen Streifen an den Enden beklebt, um darauf hinzuweisen, dass die Bahn mit Ökostrom fährt und das Klima schont.",
        ["ICE3_pride_desc"] = "Im Juli 2021 beklebte die Deutsche Bahn AG ihren Zug mit einer Regenbogenbinde um das 10-jährige Bestehen ihres LGBTIQ*-Mitarbeitenden-Netzwerks zu feiern.",
        ["ICE3_BR406_europa_desc"] = "Zur Europawahl im Jahr 2018 wurde ein Zug der Baureihe 406 auf den Namen Europa getauft und mit einem blauen Streifen beklebt.",

        ["ICE3_Apmzf403.0_name"] = "1. Kl.-Endwagen Apmzf 403.0",
        ["ICE3_Avmz403.1_name"] = "1. Kl.-Wagen Avmz 403.1",
        ["ICE3_Bvmz403.2_name"] = "2. Kl.-Wagen Bvmz 403.2",
        ["ICE3_BRmz403.3_name"] = "Bordbistro/2. Kl.-Wagen BRmz 403.3",
        ["ICE3_BRmz403.3_restaurant_name"] = "Bordrestaurant WRmz 403.3",
        ["ICE3_Bpmbz403.8_name"] = "2. Kl.-Servicewagen Bpmbz 403.8",
        ["ICE3_Bpmz403.7_name"] = "2. Kl.-Wagen Bpmz 403.7",
        ["ICE3_Bpmz403.6_name"] = "2. Kl.-Wagen Bpmz 403.6",
        ["ICE3_Bpmzf403.5_name"] = "2. Kl.-Endwagen Bpmzf 403.5",

        ["ICE3_Apmzf406.0_name"] = "1. Kl.-Endwagen Apmzf 406.0",
        ["ICE3_Avmz406.1_name"] = "1. Kl.-Wagen Avmz 406.1",
        ["ICE3_Bvmz406.2_name"] = "2. Kl.-Wagen Bvmz 406.2",
        ["ICE3_BRmz406.3_name"] = "Bordbistro/2. Kl.-Wagen BRmz 406.3",
        ["ICE3_BRmz406.3_restaurant_name"] = "Bordrestaurant BRmz 406.3",
        ["ICE3_Bpmbz406.8_name"] = "2. Kl.-Servicewagen Bpmbz 406.8",
        ["ICE3_Bpmz406.7_name"] = "2. Kl.-Wagen Bpmz 406.7",
        ["ICE3_Bpmz406.6_name"] = "2. Kl.-Wagen Bpmz 406.6",
        ["ICE3_Bpmzf406.5_name"] = "2. Kl.-Endwagen Bpmzf 406.5",

        ["ICE3_fake_menu"] = "ICE 3 (BR 403/BR 406) FAKE",
		["ICE3_BR403_1_fake_name"] = "ICE 3 (BR 403 - 1. Serie) FAKE",
        ["ICE3_BR403_1_gruen_fake_name"] = "ICE 3 (BR 403 - 1. Serie) Ökostrom FAKE",
        ["ICE3_BR403_1_klima_fake_name"] = "ICE 3 (BR 403 - 1. Serie) Klimaschützer FAKE",
		["ICE3_BR403_2_fake_name"] = "ICE 3 (BR 403 - 2. Serie) FAKE",
        ["ICE3_BR403_2_gruen_fake_name"] = "ICE 3 (BR 403 - 2. Serie) Ökostrom FAKE",
        ["ICE3_BR403_2_klima_fake_name"] = "ICE 3 (BR 403 - 2. Serie) Klimaschützer FAKE",
        ["ICE3_BR403_1_pride_fake_name"] = "ICE 3 (BR 403 - 1. Serie) Pride",
        ["ICE3_BR406_1_fake_name"] = "ICE 3 (BR 406 - 1. Serie) FAKE",
        ["ICE3_BR406_1_gruen_fake_name"] = "ICE 3 (BR 406 - 1. Serie) Ökostrom FAKE",
        ["ICE3_BR406_1_klima_fake_name"] = "ICE 3 (BR 406 - 1. Serie) Klimaschützer FAKE",
		["ICE3_BR406_1_europa_fake_name"] = "ICE 3 (BR 406 - 1. Serie) Europa FAKE",
        ["ICE3_BR406_1_NS_fake_name"] = "ICE 3 (BR 406 - 1. Serie) Nederlandse Spoorwegen FAKE",
        ["ICE3_BR406_1_hispeed_fake_name"] = "ICE 3 (BR 406 - 1. Serie) NS hispeed FAKE",

        ["ICE3_Apmzf403.0_fake_name"] = "1. Kl.-Endwagen Apmzf 403.0 FAKE",
        ["ICE3_Avmz403.1_fake_name"] = "1. Kl.-Wagen Avmz 403.1 FAKE",
        ["ICE3_Bvmz403.2_fake_name"] = "2. Kl.-Wagen Bvmz 403.2 FAKE",
        ["ICE3_BRmz403.3_fake_name"] = "Bordbistro/2. Kl.-Wagen BRmz 403.3 FAKE",
        ["ICE3_BRmz403.3_restaurant_fake_name"] = "Bordrestaurant WRmz 403.3 FAKE",
        ["ICE3_Bpmbz403.8_fake_name"] = "2. Kl.-Servicewagen Bpmbz 403.8 FAKE",
        ["ICE3_Bpmz403.7_fake_name"] = "2. Kl.-Wagen Bpmz 403.7 FAKE",
        ["ICE3_Bpmz403.6_fake_name"] = "2. Kl.-Wagen Bpmz 403.6 FAKE",
        ["ICE3_Bpmzf403.5_fake_name"] = "2. Kl.-Endwagen Bpmzf 403.5 FAKE",

        ["ICE3_Apmzf406.0_fake_name"] = "1. Kl.-Endwagen Apmzf 406.0 FAKE",
        ["ICE3_Avmz406.1_fake_name"] = "1. Kl.-Wagen Avmz 406.1 FAKE",
        ["ICE3_Bvmz406.2_fake_name"] = "2. Kl.-Wagen Bvmz 406.2 FAKE",
        ["ICE3_BRmz406.3_fake_name"] = "Bordbistro/2. Kl.-Wagen BRmz 406.3 FAKE",
        ["ICE3_BRmz406.3_restaurant_fake_name"] = "Bordrestaurant BRmz 406.3 FAKE",
        ["ICE3_Bpmbz406.8_fake_name"] = "2. Kl.-Servicewagen Bpmbz 406.8 FAKE",
        ["ICE3_Bpmz406.7_fake_name"] = "2. Kl.-Wagen Bpmz 406.7 FAKE",
        ["ICE3_Bpmz406.6_fake_name"] = "2. Kl.-Wagen Bpmz 406.6 FAKE",
        ["ICE3_Bpmzf406.5_fake_name"] = "2. Kl.-Endwagen Bpmzf 406.5 FAKE",
		},
}
end
